server:
  port: 8080
dubbo:
  application:
    name: springboot-dubbo-member
  protocol:
    name: dubbo
    port: 28080
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.sprongbootdubbomember.services.impl