server:
  port: 8082
spring:
  application:
    name: app-member
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
#    zookeeper:
#      connect-string: localhost:2181
