server:
  port: 8083
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    #开启发布订阅
  jms:
    pub-sub-domain: true
# 自定义队列名
queue: springboot-activemq-queue
topic: springboot-activemq-topic